trigger:
  branches:
    include:
      - main

pool:
  name: 'AgentUserDefinedPool'

parameters:
- name: environment
  displayName: 'Select Environment'
  type: string
  default: Dev
  values:
    - Dev
    - Prod

variables:
- ${{ if eq(parameters.environment, 'Dev') }}:
  - template: template/variables/dev-variables.yml

- ${{ if eq(parameters.environment, 'Prod') }}:
  - template: template/variables/prod-variables.yml

stages:

- stage: Terraform
  displayName: 'Terraform ${{ parameters.environment }}'

  jobs:
  - job: Terraform_Deploy
    displayName: 'Terraform Deploy'

    steps:
    - template: template/terraform.yml