# ==============================================================================
# Prod Environment Variables for Pipeline
# ==============================================================================

variables:
  # Environment Name in Azure DevOps (Approvals & Checks ke liye)
  prodEnvironment: 'Prod'

  # Path to prod.tfvars file
  prodTfvarsFile: '$(System.DefaultWorkingDirectory)/Prod/prod.tfvars'

  # Backend state file key (Future remote backend ke liye)
  # prodBackendKey: 'prod.terraform.tfstate'
